spring:
  datasource:
#    ссылаемся на имя сервиса в docker-compose db
    url: jdbc:postgresql://localhost:5432/db
    driver-class-name: org.postgresql.Driver
    username: developer
    password: parol
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
